import { describe, expect, it } from 'vitest';

import { getCountryCode } from '../../../../lib/domain/models/Geography';

describe('Unit | Model | Geography', () => {
  describe('#getCountryCode', () => {
    it('should return country code for standard french names', () => {
      // given
      const names = [
        'France',
        'Pays-Bas',
        'Allemagne',
        'belize',
        'cote d\'ivoire',
      ];

      // when
      const codes = names.map(getCountryCode);

      // then
      expect(codes).toEqual(['FR', 'NL', 'DE', 'BZ', 'CI']);
    });

    it('should return country code for all frontend country names', () => {
      // given
      const names = [
        'Afghanistan',
        'Afrique du Sud',
        'Albanie',
        'Algérie',
        'Allemagne',
        'Andorre',
        'Angola',
        'Antigua-et-Barbuda',
        'Arabie saoudite',
        'Argentine',
        'Arménie',
        'Australie',
        'Autriche',
        'Azerbaïdjan',
        'Bahamas',
        'Bahreïn',
        'Bangladesh',
        'Barbade',
        'Belgique',
        'Belize',
        'Bénin',
        'Bhoutan',
        'Biélorussie',
        'Birmanie',
        'Bolivie',
        'Bosnie-Herzégovine',
        'Botswana',
        'Brésil',
        'Brunei',
        'Bulgarie',
        'Burkina Faso',
        'Burundi',
        'Cambodge',
        'Cameroun',
        'Canada',
        'Cap-Vert',
        'Chili',
        'Chine',
        'Chypre',
        'Colombie',
        'Les Comores',
        'Congo',
        'Îles Cook',
        'Corée du Nord',
        'Corée du Sud',
        'Costa Rica',
        'Côte d\'ivoire',
        'Croatie',
        'Cuba',
        'Danemark',
        'Djibouti',
        'République dominicaine',
        'Dominique',
        'Égypte',
        'Émirats arabes unis',
        'Équateur',
        'Érythrée',
        'Espagne',
        'Estonie',
        'Eswatini',
        'Éthiopie',
        'Fidji',
        'Finlande',
        'France',
        'Gabon',
        'Gambie',
        'Géorgie',
        'Ghana',
        'Grèce',
        'Grenade',
        'Guinée',
        'Guatémala',
        'Guinée équatoriale',
        'Guinée-Bissao',
        'Guyana',
        'Haïti',
        'Honduras',
        'Hongrie',
        'Inde',
        'Indonésie',
        'Irak',
        'Iran',
        'Irlande',
        'Islande',
        'Israël',
        'Italie',
        'Jamaïque',
        'Japon',
        'Jordanie',
        'Kazakhstan',
        'Kenya',
        'Kirghizstan',
        'Kiribati',
        'Kosovo',
        'Koweït',
        'Laos',
        'Lésotho',
        'Lettonie',
        'Liban',
        'Libéria',
        'Libye',
        'Liechtenstein',
        'Lituanie',
        'Luxembourg',
        'Macédoine du Nord',
        'Madagascar',
        'Malaisie',
        'Malawi',
        'Maldives',
        'Mali',
        'Malte',
        'Maroc',
        'Îles Marshall',
        'Maurice',
        'Mauritanie',
        'Mexique',
        'Micronésie',
        'Moldavie',
        'Monaco',
        'Mongolie',
        'Monténégro',
        'Mozambique',
        'Namibie',
        'Nauru',
        'Népal',
        'Nicaragua',
        'Niger',
        'Nigéria',
        'Niue',
        'Norvège',
        'Nouvelle-Zélande',
        'Oman',
        'Ouganda',
        'Ouzbékistan',
        'Pakistan',
        'Palaos',
        'La Palestine',
        'Panama',
        'Papouasie-Nouvelle-Guinée',
        'Paraguay',
        'Pays-Bas',
        'Pérou',
        'Philippines',
        'Pologne',
        'Portugal',
        'Qatar',
        'République centrafricaine',
        'Roumanie',
        'Russie',
        'Rwanda',
        'Saint-Christophe-et-Niévès',
        'Sainte-Lucie',
        'Saint-Marin',
        'Saint-Vincent-et-les-Grenadines',
        'Salomon',
        'Salvador',
        'Samoa',
        'Sao Tomé-et-Principe',
        'Sénégal',
        'Serbie',
        'Sierra Leone',
        'Singapour',
        'Slovaquie',
        'Slovénie',
        'Somalie',
        'Soudan',
        'Soudan du Sud',
        'Sri Lanka',
        'Suède',
        'Suisse',
        'Suriname',
        'Syrie',
        'Tadjikistan',
        'Tanzanie',
        'Tchad',
        'Tchéquie',
        'Thaïlande',
        'Timor oriental',
        'Togo',
        'Tonga',
        'Trinité-et-Tobago',
        'Tunisie',
        'Turkménistan',
        'Turquie',
        'Tuvalu',
        'UK',
        'Ukraine',
        'Uruguay',
        'USA',
        'Vanuatu',
        'Vatican',
        'Vénézuéla',
        'Vietnam',
        'Yémen',
        'Zambie',
        'Zimbabwé',
      ];

      // when
      const codes = names.map(getCountryCode);

      // then
      expect(codes, `no country code for ${names[codes.indexOf(undefined)]}`).not.toContain(undefined);
    });

    it('should return undefined for other names', () => {
      // given
      const names = [
        'Neutre',
        'Institutions internationales',
        null,
        undefined,
        'La République de Gilead',
      ];

      // when
      const codes = names.map(getCountryCode);

      // then
      expect(codes).toEqual([
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      ]);
    });
  });
});
