// j'ai pas tout compris qui dépend de qui pour les tags : acquis et tutos
module.exports = {
  'airtable_frameworks': [
    'Nom',
    'Record ID',
    'Domaines (identifiants)',                 // Refresh when touching area
    'Domaines (identifiants) (id persistant)', // Refresh when touching area
  ],
  'airtable_areas': [
    'Nom',
    'id persistant',
    'Code',
    'Titre fr-fr',
    'Titre en-us',
    'Couleur',
    'Referentiel',
    'Competences (identifiants) (id persistant)', // Refresh when touching competence
    'Competences (identifiants)', // Refresh when touching competence
    'Record ID',
    'Origine',
  ],
  'airtable_competences': [
    'Titre fr-fr',
    'Titre en-us',
    'Description fr-fr',
    'Domaine',
    'Domaine (id persistant)',
    'Sous-domaine',
    'Record ID',
    'Tubes', // Refresh when touching tube
    'Acquis (via Tubes) (id persistant)', // Refresh when touching tube
    'Description en-us',
    'Origine',
    'id persistant',
    'Thematiques', // Refresh when touching thematic
    'Origine2',
  ],
  'airtable_thematics': [
    'Nom',
    'Titre en-us',
    'Competence',
    'Tubes', // Refresh when touching tube
    'Competence (id persistant)',
    'Record Id',
    'Index',
    'Tubes (id persistant)', // Refresh when touching tube
  ],
  'airtable_tubes': [
    'Nom',
    'Description',
    'Titre',
    'Titre pratique fr-fr',
    'Titre pratique en-us',
    'Description pratique fr-fr',
    'Description pratique en-us',
    'id persistant',
    'Record Id',
    'Competences',
    'Competences (id persistant)',
    'Acquis', // Refresh when touching skills
    'Thematiques',
    'Index',
  ],
  'airtable_skills': [
    'Nom',
    'id persistant',
    'Record Id',
    'Status',
    'PixValue',
    'Version',
    'Indice fr-fr',
    'Indice en-us',
    'Statut de l\'indice',
    'Comprendre', // Refresh when touching tutorials
    'Comprendre (id persistant)', // Refresh when touching tutorials
    'En savoir plus', // Refresh when touching tutorials
    'En savoir plus (id persistant)', // Refresh when touching tutorials
    'Description',
    'Statut de la description',
    'Level',
    'Tube',
    'Compétence (via Tube) (id persistant)',
    'Internationalisation',
    'Tube (id persistant)',
    'Date',
    'Epreuves (id persistant)', // Refresh when touching challenges
    'Tags',
  ],
  'airtable_challenges': [
    'Consigne',
    'Propositions',
    'Type d\'épreuve',
    'Preview',
    'Record ID',
    'Bonnes réponses',
    'Type péda',
    'Auteur',
    'Timer',
    'Déclinable',
    'T1 - Espaces, casse & accents',
    'T2 - Ponctuation',
    'T3 - Distance d\'édition',
    'Généalogie',
    'Statut',
    'Acquix',
    'Embed URL',
    'Embed title',
    'Embed height',
    'Version prototype',
    'Version déclinaison',
    'Non voyant',
    'Daltonien',
    'Spoil',
    'Responsive',
    'Géographie',
    'Format',
    'id persistant',
    'Acquix (id persistant)',
    'Langues',
    'Réponse automatique',
    'Consigne alternative',
    'files', // Refresh when touching attachments ?
    'Bonnes réponses à afficher',
    'Focalisée',
    'Difficulté calculée',
    'Discrimination calculée',
    'updated_at',
  ],
  'airtable_tests': [
    'Nom',
    'id persistant',
    'Description',
    'Statut',
    'Ordre affichage',
    'Épreuves',
    'Épreuves (id persistant)',
    'Image',
    'Preview',
    'Nb d\'épreuves',
    'Acquis',
    'Record ID',
    'Adaptatif ?',
    'Défi de la semaine ?',
    'Series',
    'Competence',
    'Competence (id persistant)',
    'Epreuves copy',
    'Epreuves copy',
    'Field 17',
    'Campagne ID',
  ],
  'airtable_tags': [
    'Nom',
    'Record ID',
    'id persistant',
    'Description',
    'Notes',
    'Acquis', // Refresh when touching skills
    'Tutoriels', // Refresh when touching tutorials
  ],
  'airtable_tutorials': [
    'Tags',
    'Titre',
    'id persistant',
    'Format',
    'Durée',
    'Source',
    'Lien',
    'License',
    'niveau',
    'Date maj',
    'CoupDeCoeur',
    'Record ID',
    'Langue',
  ],
  'airtable_attachments': [
    'filename',
    'size',
    'alt',
    'url',
    'mimeType',
    'type',
    'challengeId', // Refresh when touching challenge ?
    'Record ID',
    'challengeId persistant', // Refresh when touching challenge ?
  ],
};
