import { Skill } from '../../../../lib/domain/models/index.js';

export function buildSkill({
  id = 'skillIdPersistant',
  airtableId = 'recTIddrkopID28Ep',
  name = '@accesDonnées1',
  description = 'skill description',
  descriptionStatus = Skill.DESCRIPTION_STATUSES.VALIDE,
  hint_i18n = {
    fr: 'Peut-on géo-localiser un téléphone lorsqu’il est éteint ?',
    en: 'Can we geo-locate a rabbit on the ice floe?',
  },
  hintStatus = Skill.HINT_STATUSES.VALIDE,
  tutorialIds = ['receomyzL0AmpMFGw'],
  tutorialAirtableIds = ['recAQdadalfhnasl'],
  learningMoreTutorialIds = ['recQbjXNAPsVJthXh', 'rec3DkUX0a6RNi2Hz'],
  learningMoreTutorialAirtableIds = ['recLhadqwqqwcqufdq', 'rec0LQAWDcqacqjwl'],
  competenceId = 'recofJCxg0NqTqTdP',
  pixValue = 2.4,
  status = 'actif',
  tubeId = 'recTU0X22abcdefgh',
  tubeAirtableId = 'rec123flALDJWQDC',
  level = 5,
  internationalisation = Skill.INTERNATIONALISATIONS.MONDE,
  version = 1,
  challengeIds = ['challenge0aADHQIWCQ123', 'challengeLQdqjcpoqnefc'],
  createdAt = '2025-01-06T08:58:57.465Z',
  activatedAt = null,
  archivedAt = null,
  obsoletedAt = null,
} = {}) {
  return new Skill({
    id,
    airtableId,
    name,
    description,
    descriptionStatus,
    hint_i18n,
    hintStatus,
    tutorialIds,
    tutorialAirtableIds,
    learningMoreTutorialIds,
    learningMoreTutorialAirtableIds,
    competenceId,
    pixValue,
    status,
    tubeId,
    tubeAirtableId,
    level,
    internationalisation,
    version,
    challengeIds,
    createdAt,
    activatedAt,
    archivedAt,
    obsoletedAt,
  });
}
