import { Skill } from '../../../../lib/domain/models/index.js';

export function buildSkill({
  id = 'skillIdPersistant',
  name = '@accesDonnées1',
  description = 'skill description',
  descriptionStatus = Skill.DESCRIPTION_STATUSES.VALIDE,
  hint_i18n = {
    fr: 'Peut-on géo-localiser un téléphone lorsqu’il est éteint ?',
    en: 'Can we geo-locate a rabbit on the ice floe?',
  },
  hintStatus = Skill.HINT_STATUSES.VALIDE,
  tutorialIds = ['receomyzL0AmpMFGw'],
  learningMoreTutorialIds = ['recQbjXNAPsVJthXh', 'rec3DkUX0a6RNi2Hz'],
  competenceId = 'recofJCxg0NqTqTdP',
  status = 'actif',
  tubeId = 'recTU0X22abcdefgh',
  level = 5,
  internationalisation = Skill.INTERNATIONALISATIONS.MONDE,
  version = 1,
  challengeIds = ['challenge0aADHQIWCQ123', 'challengeLQdqjcpoqnefc'],
  createdAt = '2025-01-06T08:58:57Z',
  activatedAt = null,
  archivedAt = null,
  obsoletedAt = null,
} = {}) {
  return new Skill({
    id,
    airtableId: id,
    name,
    description,
    descriptionStatus,
    hint_i18n,
    hintStatus,
    tutorialIds,
    tutorialAirtableIds: tutorialIds,
    learningMoreTutorialIds,
    learningMoreTutorialAirtableIds: learningMoreTutorialIds,
    competenceId,
    status,
    tubeId,
    tubeAirtableId: tubeId,
    level,
    internationalisation,
    version,
    challengeIds,
    createdAt: typeof createdAt === 'string' ? new Date(createdAt) : createdAt,
    activatedAt,
    archivedAt,
    obsoletedAt,
  });
}
