const Skill = require('../../../../lib/domain/models/Skill');

const buildSkill = function({
  id = 'recTIddrkopID28Ep',
  name = '@accesDonnées1',
  hintFrFr = 'Peut-on géo-localiser un téléphone lorsqu’il est éteint ?',
  hintEnUs = 'Can we geo-locate a rabbit on the ice floe?',
  hintStatus = 'Validé',
  tutorialIds = ['receomyzL0AmpMFGw'],
  learningMoreTutorialIds = ['recQbjXNAPsVJthXh', 'rec3DkUX0a6RNi2Hz'],
  competenceId = 'recofJCxg0NqTqTdP',
  pixValue = 2.4,
  status = 'actif',
  tubeId = 'recTU0X22abcdefgh',
  description = 'skill description',
  level = 5,
  internationalisation = 'Monde',
  version = 1,
  locale = 'fr-fr',
} = {}) {
  return new Skill({
    id,
    name,
    hintFrFr,
    hintEnUs,
    hintStatus,
    tutorialIds,
    learningMoreTutorialIds,
    competenceId,
    pixValue,
    status,
    tubeId,
    description,
    level,
    internationalisation,
    version,
  }, locale);
};

buildSkill.withLocaleFr = function({
  id,
  name,
  hint,
  hintStatus,
  tutorialIds,
  learningMoreTutorialIds,
  competenceId,
  pixValue,
  status,
  tubeId,
  description,
  level,
  internationalisation,
  version,
} = {}) {
  return new Skill({
    id,
    name,
    hintFrFr: hint,
    hintEnUs: null,
    hintStatus,
    tutorialIds,
    learningMoreTutorialIds,
    competenceId,
    pixValue,
    status,
    tubeId,
    description,
    level,
    internationalisation,
    version,
  }, 'fr');
};

buildSkill.withLocaleFrFr = function({
  id,
  name,
  hint,
  hintStatus,
  tutorialIds,
  learningMoreTutorialIds,
  competenceId,
  pixValue,
  status,
  tubeId,
  description,
  level,
  internationalisation,
  version,
} = {}) {
  return new Skill({
    id,
    name,
    hintFrFr: hint,
    hintEnUs: null,
    hintStatus,
    tutorialIds,
    learningMoreTutorialIds,
    competenceId,
    pixValue,
    status,
    tubeId,
    description,
    level,
    internationalisation,
    version,
  }, 'fr-fr');
};

buildSkill.withLocaleEnUs = function({
  id,
  name,
  hint,
  hintStatus,
  tutorialIds,
  learningMoreTutorialIds,
  competenceId,
  pixValue,
  status,
  tubeId,
  description,
  level,
  internationalisation,
  version,
} = {}) {
  return new Skill({
    id,
    name,
    hintFrFr: null,
    hintEnUs: hint,
    hintStatus,
    tutorialIds,
    learningMoreTutorialIds,
    competenceId,
    pixValue,
    status,
    tubeId,
    description,
    level,
    internationalisation,
    version,
  }, 'en');
};
module.exports = buildSkill;
