module.exports = {
  buildArea: require('./build-area'),
  buildAreaAirtableDataObject: require('./build-area-airtable-data-object'),
  buildAttachment: require('./build-attachment'),
  buildChallengeAirtableDataObject: require('./build-challenge-airtable-data-object'),
  buildChallengeForRelease: require('./build-challenge-for-release'),
  buildCompetence: require('./build-competence'),
  buildCompetenceAirtableDataObject: require('./build-competence-airtable-data-object'),
  buildCourse: require('./build-course'),
  buildCourseAirtableDataObject: require('./build-course-airtable-data-object'),
  buildFramework: require('./build-framework'),
  buildRelease: require('./build-release'),
  buildSkill: require('./build-skill'),
  buildSkillAirtableDataObject: require('./build-skill-airtable-data-object'),
  buildThematic: require('./build-thematic'),
  buildThematicAirtableDataObject: require('./build-thematic-airtable-data-object'),
  buildTube: require('./build-tube'),
  buildTubeAirtableDataObject: require('./build-tube-airtable-data-object'),
  buildTutorial: require('./build-tutorial'),
  buildTutorialAirtableDataObject: require('./build-tutorial-airtable-data-object'),
};
