module.exports = {
  buildAreaForRelease: require('./build-area-for-release'),
  buildAreaDatasourceObject: require('./datasource-objects/build-area-datasource-object'),
  buildAttachment: require('./build-attachment'),
  buildChallengeDatasourceObject: require('./datasource-objects/build-challenge-datasource-object'),
  buildChallengeForRelease: require('./build-challenge-for-release'),
  buildCompetenceForRelease: require('./build-competence-for-release'),
  buildCompetenceDatasourceObject: require('./datasource-objects/build-competence-datasource-object'),
  buildContentForRelease: require('./build-content-for-release'),
  buildCourseForRelease: require('./build-course-for-release'),
  buildCoursePostgresDataObject: require('./build-course-postgres-data-object'),
  buildDomainRelease: require('./build-real-release'),
  buildFrameworkForRelease: require('./build-framework-for-release'),
  buildFrameworkDatasourceObject: require('./datasource-objects/build-framework-datasource-object'),
  buildRelease: require('./build-release'),
  buildSkillForRelease: require('./build-skill-for-release'),
  buildSkillDatasourceObject: require('./datasource-objects/build-skill-datasource-object'),
  buildStaticCourse: require('./build-static-course'),
  buildThematicForRelease: require('./build-thematic-for-release'),
  buildThematicDatasourceObject: require('./datasource-objects/build-thematic-datasource-object'),
  buildTubeForRelease: require('./build-tube-for-release'),
  buildTubeDatasourceObject: require('./datasource-objects/build-tube-datasource-object'),
  buildTutorialForRelease: require('./build-tutorial-for-release'),
  buildTutorialDatasourceObject: require('./datasource-objects/build-tutorial-datasource-object'),
};
