module.exports = {
  buildArea: require('./build-area'),
  buildAreaAirtableDataObject: require('./build-area-airtable-data-object'),
  buildCourse: require('./build-course-airtable-data-object'),
  buildFramework: require('./build-framework'),
  buildRelease: require('./build-release'),
  buildChallenge: require('./build-challenge-airtable-data-object'),
  buildChallengeForRelease: require('./build-challenge-for-release'),
  buildCompetence: require('./build-competence-airtable-data-object'),
  buildAttachment: require('./build-attachment'),
  buildSkill: require('./build-skill-airtable-data-object'),
  buildTube: require('./build-tube-airtable-data-object'),
  buildTutorial: require('./build-tutorial-airtable-data-object'),
  buildThematic: require('./build-thematic'),
};
