module.exports = {
  airtableBase:"BASE",
  airtableWorkbenchBase:"BASE",
  airtableEditorBase:"BASE",
  airtableUrl:"URL",
  tableChallenges:"TABLE",
  tableSkills:"TABLE",
  tableWorkbench:"TABLE",
  storagePost:"URL",
  storageTenant:"ID",
  storageUser:"USER",
  storagePassword:"PASSWORD",
  storageKey:"KEY",
  storageAuth:"URL",
  pixStaging:"URL",
  pixWorkbench:"URL",
  pixWorkbenchUser:"user",
  pixWorkbenchPassword:"password"
};