import { Factory } from 'ember-cli-mirage';

export default Factory.extend({

  instructions: 'instructions',
  type: 'QCU',
  format: 'format',
  suggestion: 'suggestion',
  answers: 'answers',
  t1: 't1',
  t2: 't2',
  t3: 't3',
  illustration: undefined,
  attachments: undefined,
  pedagogy: 'pedagogy',
  author: 'author',
  declinable: 'declinable',
  version: 'version',
  genealogy: 'Prototype 1',
  skillNames: 'skillNames',
  status: 'validé',
  preview: 'preview',
  pixId: 'pixId',
  scoring: 'scoring',
  timer: 'timer',
  embedURL: 'embedURL',
  embedTitle: 'embedTitle',
  embedHeight: 'embedHeight',
  alternativeVersion: 'alternativeVersion',
  accessibility1: 'accessibility1',
  accessibility2: 'accessibility2',
  spoil: 'spoil',
  responsive: 'responsive',
  alternativeText: 'alternativeText',
  languages: 'languages',
  area: 'area',
  _definedBaseName: '_definedBaseName',
  autoReply: 'autoReply',
});

