name: pr title check

on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: 1024pix/pix-actions/check-pr-title@b4d102041ba82f1304923ae5ea3d2fc2c477e8fe # main