name: "Security Checks"

on:
  push:
    branches:
      - dev

jobs:
  upload_sboms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: "package.json"

      - name: Install Cyclone DX
        run: npm install -g @cyclonedx/cyclonedx-npm@4.2.0

      - name: Pix Editor Monorepo - Install dependencies
        run: npm ci

      - name: Pix Editor Monorepo - Create SBOM
        id: create_monorepo_sbom
        continue-on-error: true
        run: npx @cyclonedx/cyclonedx-npm --output-file pix-editor-repo-sbom.json package.json

      - name: Pix Editor Monorepo - Upload BOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
        if: ${{ steps.create_monorepo_sbom.outcome == 'success' }}
        continue-on-error: true
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          # change these variables for each project
          projectName: Pix Editor Monorepo
          projectVersion: dev
          bomFilename: "pix-editor-repo-sbom.json"
          autoCreate: true

      - name: Pix Editor front - Create SBOM
        id: create_front_sbom
        continue-on-error: true
        run: npx @cyclonedx/cyclonedx-npm --output-file pix-editor-front-sbom.json pix-editor/package.json

      - name: Pix Editor front - Upload BOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
        if: ${{ steps.create_front_sbom.outcome == 'success' }}
        continue-on-error: true
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          # change these variables for each project
          projectName: Pix Editor front
          projectVersion: dev
          bomFilename: "pix-editor-front-sbom.json"
          autoCreate: true

      - name: Pix Editor API - Create SBOM
        id: create_api_sbom
        continue-on-error: true
        run: npx @cyclonedx/cyclonedx-npm --output-file pix-editor-api-sbom.json api/package.json

      - name: Pix Editor API - Upload BOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
        if: ${{ steps.create_api_sbom.outcome == 'success' }}
        continue-on-error: true
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          # change these variables for each project
          projectName: Pix Editor API
          projectVersion: dev
          bomFilename: "pix-editor-api-sbom.json"
          autoCreate: true

      - name: Pix Editor Challenge-Parser - Install dependencies
        working-directory: challenge-parser
        run: npm ci

      - name: Pix Editor Challenge-Parser - Create SBOM
        id: create_challenge_parser_sbom
        continue-on-error: true
        run: npx @cyclonedx/cyclonedx-npm --output-file pix-editor-challengeparser-sbom.json challenge-parser/package.json

      - name: Pix Editor Challenge-Parser - Upload BOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5
        if: ${{ steps.create_challenge_parser_sbom.outcome == 'success' }}
        continue-on-error: true
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          # change these variables for each project
          projectName: Pix Editor Challenge-Parser
          projectVersion: dev
          bomFilename: "pix-editor-challengeparser-sbom.json"
          autoCreate: true
